# SQLite connection (point to the same Django SQLite file)
spring.datasource.url=jdbc:sqlite:C:/Users/Blessings Chongo/Cerberus/Api/db.sqlite3
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
server.port=8081