# Generated by Django 6.0.7 on 2026-07-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('CPU_Usage', 'CPU Usage'), ('Available_RAM', 'Available RAM'), ('Disk_Free_C', 'Disk Free C'), ('Process_', 'Process Status'), ('METRICS_AGGREGATE', 'Aggregate Metrics')], max_length=50)),
                ('value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
